# Generated by Django 4.1.1 on 2022-09-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_alter_movie_director_alter_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
